### PR TITLE
Added main file for usage in node scripts...

### PR DESCRIPTION
**Pull request by Sir-Will**
I wanted to use this module in my gulp script, but I didn't see any option to run it without a command. So I have added the missing main file and few modifications to support it.

I also did the following changes:
- Added option to define source directory
- Added basic jest tests
- Updated shelljs to fix warn spam

@Morik thoughts on getting your fork merged into the original and updated on npm?

### CODE REVIEW

**Comment by Morik** [comment]
Hello @Sir-Will,

thanks for your help. To be honest, I'm not an expert to NodeJS development and was only interested to get the Script running for our own development.
As far as I can tell your changes make sense so far, so if you're ready to merge tell me and I'll try to merge it to the original repo.
But as I have no control over it, I can't guarantee for that to happen.

**Comment by Sir-Will** [comment]
Hey, thanks for your reply.
I can create a PR directly from my fork to the original, including your changes, if that's okay with you?
Would probably make it easier.

**Comment by Morik** [comment]
Feel free to include our changes in your PR to @padarom

**Comment by Sir-Will** [comment]
Thanks. I have opened a new PR here: https://github.com/padarom/wspackager/pull/9

**Pull request closed without merging**
